Repository googleapis/python-vision, pull requests merged in 2021-09, with the labels that each got.

#223 chore: fix typo
  UPGRADING.md
Labels: api: vision, cla: yes, automerge: exact

#227 chore: reference main branch of google-cloud-python
  README.rst
Labels: api: vision, cla: yes

#234 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: api: vision, cla: yes, automerge

#235 chore: remove duplicate word in README
  README.rst
Labels: api: vision, cla: yes
