Repository googleapis/python-vision, pull requests merged in 2021-04, with the labels that each got.

#130 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: vision, cla: yes, context: full

#133 docs: insert empty lines between methods in generated docs
  docs/_static/custom.css
Labels: api: vision, cla: yes

#137 chore: prevent normalization of semver versioning
  setup.py
Labels: api: vision, automerge, cla: yes

#139 chore(revert): revert preventing normalization
  setup.py
Labels: api: vision, automerge, cla: yes
